openapi: 3.0.0
info:
  title: Widget Transformation Project API
  version: 1.0.0
paths:
  /api/v1/routes/usage:
    get:
      summary: Get route usage data
      responses:
        '200':
          description: A list of route usage data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RouteData'
  /api/v1/routes/models:
    get:
      summary: Get model usage tracking
      responses:
        '200':
          description: A list of model usage data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RouteData'
  /api/v1/routes/configure:
    post:
      summary: Configure a route
      responses:
        '200':
          description: Route configured successfully
  /api/v1/cost/optimizations:
    get:
      summary: Get cost optimization suggestions
      responses:
        '200':
          description: A list of cost optimization suggestions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostOptimization'
  /api/v1/cost/apply-optimization:
    post:
      summary: Apply cost savings
      responses:
        '200':
          description: Cost savings applied successfully
  /api/v1/performance/alerts:
    get:
      summary: Get performance alerts
      responses:
        '200':
          description: A list of performance alerts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PerformanceAlert'
  /api/v1/performance/resolve-alert:
    post:
      summary: Resolve alerts
      responses:
        '200':
          description: Alert resolved successfully
  /api/v1/providers/health-check:
    get:
      summary: Provider health check
      responses:
        '200':
          description: Provider health check status
  /api/v1/providers/switch:
    post:
      summary: Switch provider
      responses:
        '200':
          description: Provider switched successfully
  /api/v1/forecast/cost-usage:
    get:
      summary: Cost and usage forecast
      responses:
        '200':
          description: Cost and usage forecast data
components:
  schemas:
    RouteData:
      type: object
      properties:
        route:
          type: string
        requests:
          type: integer
        configuredModel:
          type: string
        actualModel:
          type: string
        cost:
          type: number
        avgResponseTime:
          type: number
        successRate:
          type: number
        recentLogs:
          type: array
          items:
            type: object
        status:
          type: string
    CostOptimization:
      type: object
      properties:
        totalSavings:
          type: number
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/OptimizationRecommendation'
        currentMonthlyCost:
          type: number
        projectedMonthlyCost:
          type: number
    OptimizationRecommendation:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        savings:
          type: number
        action:
          type: string
        status:
          type: string
    PerformanceAlert:
      type: object
      properties:
        id:
          type: string
        severity:
          type: string
        title:
          type: string
        description:
          type: string
        action:
          type: string
        impact:
          type: string
        timestamp:
          type: string
          format: date-time
        resolved:
          type: boolean